[project]
name = "PySide Widgets Project"

[tool.pyside6-project]
files = ["anggota.py", "anggota.ui", "buku.py", "buku.ui", "database.py", "form.py", "form.ui", "main.py", "peminjaman.py", "peminjaman.ui", "petugas.py", "petugas.ui"]
